# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: DotNetCoreCLI@2
    displayName: "Restore NuGet packages"
    inputs:
      command: "restore"

  - task: DotNetCoreCLI@2
    displayName: "Build the project in $(BuildConfiguration) mode"
    inputs:
      command: "build"
      projects: "**/*.csproj"
      arguments: "--configuration $(BuildConfiguration) --no-restore"

  - task: DotNetCoreCLI@2
    displayName: "Publish the project in $(BuildConfiguration) mode"
    inputs:
      command: "publish"
      publishWebProjects: true
      arguments: "--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)"

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: $(Build.ArtifactStagingDirectory)
      ArtifactName: "Adventure-Works-API"

  - task: AzureRmWebAppDeployment@4
    displayName: "Deploy the project to $(WebApplicationName) Web App"
    inputs:
      ConnectionType: AzureRM
      azureSubscription: $(AzureSubscription)
      appType: webApp
      WebAppName: $(WebApplicationName)
      packageForLinux: $(System.DefaultWorkingDirectory)/**/*.zip
